# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6dhkcrZjLwNevifQed9/ftML1inZ2oOJ9NSinZeFRNdFqtWOuPXee03bmOlufcowJ/Uj/9lt2dcwPqSCcAOBsInej3k4Vw9CoSpxsPVVK8H0CQYx/kT3dQw145rJHuXrS2wZYH5tftp45c9XeZprFf44S7+8eOstYVV1X9Zk6rqvo/eTPIDpc8hUelsy74tELYmmINDJEgQo8aB+zihBkv5S/xsA1EnvF78ndD39/aAM9kfhiQ==,iv:pI2dAj+FYQIR2qxCwhif42Uq3CKdqAgkSrkIExG2JXo=,tag:gV3ZEbbyLsue71Af/rQj5g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL3RzMFNKWmJkNnY5c0Ix
        RDI2ZW4wdnZrSE54ayt4TFVVM2RRenpuc1VJCi9xZ2NxRitSNFpBSnZnVHhEK0J2
        UjBIMG9XU21YMXZoTFRzRm9DTUt2ZDgKLS0tIHkram1PR0doSDhEZVMzbFllamJV
        aEJPdmllVXJIRWNJS2RiRlJ0b2RwLzgK7BgNsNXXc60c7LIlZrxFJrGbrEcIFSnl
        u+uQOy+NwbcIJPny6h3G9gIetgIjmWN+EDA1ZOjhKpuXuF9wgpHpug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-09T11:02:49Z"
  mac: ENC[AES256_GCM,data:jisT0niKynz32/Kv61S15gz9IMX4CyetG/mqKVZynDs6es8e5XluWtCdM9TNMPON4lOuCuO0uNB5bXP2gcQ/BnIdfJ9AGuZmVfbymm9J0QUlFWI6ZOg4FVimWXh+RJblXllTLgpfQQ1CFysG7a0bxjKajMesmPGFiKnW0t2T/Po=,iv:g4DtP4sZ1T12r/6j5ov6ZBHUMS8CcsSMf6htO2VGcpI=,tag:OvnVaGbDRKMSImowZ3b65Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
