# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Nrpio44ZW5zKBjcWtBJtWQDZlMx9HrP0KZ/eEKxdY+JX/pyVa95IM6shXcpCr5e5fYCCr20Xzo6pqiMmiojDZK9mDLz0nXujl/Sc6e/n64vNr6thi0S05mKGDVjUA0ykuxzVNb2d0vqqanxbvQKLSzQTeo399V29Ks1koGrY6+i90FtxY/Rj9On5zp3cCI+xlB64jD5WRCHHLgtE0YGQE9BmSM8advkYe2czT4i7c7m4CPzWtg==,iv:iDE1NrImcEWHPGsVjR5ROWDkAPqkWIwbnrvSVnFco/8=,tag:6uxYe7bgmVNm063F0XWdMw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUWxBbGU4Sk1NZEg4cDQ5
        cXQybjNXamM1b1FNdlA4ejBOalBJLy93dld3CmxlSzZnS3ZSOThtZUdHMTRZbjNl
        a0tmVUtNRWZyaUxKZjdVb0t5clJ2eU0KLS0tIGh0OUdqWWJ1ZVNvYmVYd3hMRU1x
        UmEzNHhacGJUMmF5YlZMN20vS0l3Z2sKv8qbkuea5JxW6CdJ6y8f1MXKurrOEVt4
        /emgtnWhvR2TYiFpcRX7yN5+bPXegMQ1VMGYlbLMQohvCICqv24Bxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T14:50:14Z"
  mac: ENC[AES256_GCM,data:42FyyWvNmIn8jg5aOWdxDoyChVc4PglIUXgGVjapcaKuPMlRn1+wMUm7QFuoZHLhYVuZdOxBtaATnQQAdhuUQrjEpqSRZDoBuLzut7E11BURk4TxDgocC/f+IPPp9GCstxDEqmZM2Qhrtz49ltk4e7XwJKdm6piBVz1+rbI98Dk=,iv:yT/jT81WbQLqniy86mkLvxXTJTTkbw2bImQEt4oEtNs=,tag:7bL7VGuWCgjxV0dUjUKQDQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
