# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Ht5bsmqvJyG7mvvUI1HGn3gVbYBgn5MSqJALqrjqtTIAEnxDPxKMzrsM,iv:lA14m0UljwNsUrn0Zt/rogW8kvFgKwF2lKqRZexRXSQ=,tag:FRcvn7e9V0B7CtNX2IWKzA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOU9wRmN5TzF5N1NpbkVE
        K01kZkJwVU1YM0cyanMxU0YyZ0VoZm5mSng0CngxWEFzeTFMTjZyWG5yVExXOFdG
        K3pQdkwzVGxab2d4WER0WXBTUHBPVmsKLS0tIEZ0MVVIWGdkQkNHek1yaTdFTFBG
        VmJHdEhESmdOV09oZ1ExZy95L3o3UHcKbpDmyUChqAgQ5RnrJaP5L+fI0uhK560C
        EU0qxi8/572O4ez6/A7SlaSThT1EsMwzzRettIxPCACTf+pdFuZM2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-07T18:31:52Z"
  mac: ENC[AES256_GCM,data:6H5Pnk9XHXeeSv5xaCdMRb/dxPdaRQvCzI0LzKX3BvIDmoPHtBkLjMj4g0U8csI92b5lWlSYnwy/IEQZgyJC6VPrFH25vLafu8RtCUa+r+YJYbF0gF0mw8xTjJ4L1FmVGPHsXcG8oBG8lth/Vuat9NTPbx5/7jbDYIDsX8sM5xo=,iv:zTYqEQXRy2DKuQC4AFBUGqC1FhDP2lDiNqsrMnmNcx4=,tag:n/LzDr5Ua0qKGsm+a4JH7w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
