# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:V80U9CnM3G7dX92cKzopd/8pBFXesGM+8+NHb2ar90dU3P++yHF8OsBbZTLi7yBVFHP8nKYVEFAopZYmjzlxLQe4SVJu8neEgfmI9E4SZ65pgkoPTa0b+5NormqIVrz6Idi3T0xMxqAgJFm1U2Ux/M1E89SSPmCtRPypJrfwchk46B8Wb/L1Hd4oknX+bmlkSkWPOB6GjolbI/ArRZ0kFEczbZPHWcjnthZHDVNR6fsjX6qEALL62g==,iv:nl5vYiTVcI6RST1DQGJkv2v8//SuRDlVkACnilRP+RU=,tag:/ycGA3Wx3Rl2VD9NU8aN9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bWE5SkZBK1p6MlJPODhn
        eWVUdDg2ejFpUG52eDJwOXd1WW41RmFqdUZnCjFLQ3BoLzc2d3JNeDhncnQrWWpt
        eFlXMGNqTllvYjZrWHpDVFQ4NTdBdncKLS0tIGhTY0U4dnNzeXpsdm1zMTlZUmNL
        UlR2UzRzMVRrUUt3UkQwQ3FMbmZlaWMKqjv5FejbLAmNgiGEovi7SD05VLDMIFbp
        wzddVS94P3R70DLdqoFxCCHPDg81TZhcBh5QAYywSF48w97wiXE8KQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-25T15:40:10Z"
  mac: ENC[AES256_GCM,data:MDdUb58aDviPrKyWSZUIYSQDRRc8c5u0CoFoVoKo/VKGlKi7sEi/mkncnNRjoBvy9LKE2SXNsnBusVo7GxUlRJRY1BMhrM3ObA3SjOZjtwNhTS5RXfMohozYMvdYt/+AJTAXcyAp6aeg7VX/720mM1vdkxKxtr8I2aQcevgz/BM=,iv:nSqknJoTIjMHMeLCNzzFzB/fBPRQLrOAeK9oWzGQsrA=,tag:DQlBpwHRLO3Tl05FXCZKjw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
