---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjws.yaml
  - ./oci-external-dns.yaml
  - ./external-secrets.yaml
  - ./onepassword-connect.yaml
  - ./rook-ceph-cluster.yaml
  - ./rook-ceph.yaml