apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:QF8JRSE+9z5yRkH1n/hl4U+wB4oa9JqHlvZ/H72gatDaVD1R8mnMyMY7gr4PqCgHBJxd+2oAADT+qRn5o83iH/w0Cd0lzsDoVBp5t0TLCjXVuoRO05Q9pW/Ufs15gIvkjU30oW88Vz93piueXsN6o9Xs092PD8bPHiXaX2JdBYX+uT8yz7GHTMN637BscaB2QZOXhW/G2UlcA3KSt6sqNew0nqki0Ei1FxrLaicflwJ37/0kaX/l9o/jaBVlQjDSQR41Sk+eJKlm/WSUKajfHmKQUuBh6KMZJJPN5HyEMKcTR17C/QHz7kPbnFTwRH+kEFBPHGcMABmTlLDAWe0EP/Q1LZE4lkd6SOrrVMZyZ3eiz/jC1bMbkXPgbQfAuL4zcWX8OspDMcnlxXGsQsEi0GRSsY5N2FXheicwpMi7P4JcMoRsrXECOEatX8fzqb1V7AaAClzOYDJjahIF3BcTkUVyqxZpRRSRwLXMMkLjoEIuDoS1W4niH0Gk/GbuJiUNnqeEdfGvKi5S3pPiAaJLwO2gSVeSQ3v9BhYZ6nOG7LKtBBzlj4QlUtPWWCetX0Ccvq6TrBYnZBvZrFpkL01meelaSBzyh3v9TIGGubuqukeru3nfLdWGvy0OjueL+TfT5DYTcOQGXQfMQAztugaKH0K6C3rmx2RXxri9Aw6wdAvOFt+r0AVxiQIA1kcjUOEqA4ZJV2QDhR888nN1sIQ+mZsAaEkF5EysUbo6wGLM4dnNOo5wNNoMZHGFtnXDVaWmAdudrQ7I5iYw1dBGQnFJBXT0EkCOPKsaRHorIaHeLYzDoplyGYAp/IFSdcdz9DvjOfUOjD6eET3E2Jn6xJm6xDgYGneXlj8u1nPol2lzz5GP8nRWD24UjcqvfJv43mQlPh2hISPRpdC7AHo8ZESeOrkVgo2t8QcWlxOpjL81c9YIXxgJ6sbbuwJ1zTyyCH3jBE6eJWEZBTsoCfBAptOTHB2uMwP9T8VIH0vl1OqRKwvT8qGmIIJVEs0EdW4M3YJcqL6x90IOrReJcoI3qOcI+VWW7BkjkpZGMMXP+4Eln6iZRbJoBv8bbAU1DQnF8kITYD8a7orWiB9yDXW9ANBaKwhCH2a7lE+mH6fEOcFSB6tYP3IBAZdObAudPTg=,iv:edoK1v11L0yXYjPHa/e7i9ib1HPePnVsTCvnLvjDl8c=,tag:TVtSKP/DmJILimPWKcdQGg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV2NrUVhEN2F0VG01MEZF
        WnhkaWtlc1E5b3dqeUhhaXQvQWtOSndhSFVzCnhlVnVEMnZ1WjFwNC9JbGxwRm1t
        TThSaWF5N1AzSHVxenN6SlljVUkrc1EKLS0tIFVhaEV2TFpXbzBydS9sdkptNG1Y
        cXpERHZoWm1MVllQamNNTmh5R0xpT28Kfl5CHKfZE5rKzkniImumIgdb8BTy/iXZ
        My0AJv4kMcu6fo9JrWDlZ5z9Srzvr6eXsqLo1wCb0mOXlAeJqqQEEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-11T14:33:15Z"
  mac: ENC[AES256_GCM,data:Ns6xBo2gCYDZ+RRPlAJNQPTm891gz7NnowYP41YC+zf8MLitan8us9zeNwF/U2rSUju5g1iVKT+8CXmTTC0HN8E3FuKKb7pbGvux3jggg2SXaAeNOkKTgt5SKGD+pJHuy2Ugd7mfBtwhKdWBdoqJBfoEkIHbe7oeFsrpnba+9wQ=,iv:hjdjxS15bpTRSLJ9RqMFacKFAHu/qwnd2hCcT+ALveU=,tag:SK1q7W3TZhaI2FyHgK66cg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
