apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:z4IQTgNSitEmlPnYIu9AOjlWJ8O4E2gvfiJEf6BQUzc5QoEmLeCX5VMNPSZxTs0MOYCuOp7wwx4ol6jB+wF2P9afAkD30WzXKEL5Sh3qdSsFFj3WI+v5VEf73kgH0mRXyTpOurcxc41cF1KBxkKoim1VgBTJhC0tYrYPpCM788K9mbvJ2GdNY4PFdBf3yJRi3aIT5SXyFYa9tUY+VE6xNDSKjqycyvNtQQe1OciRQia/kBUXY9pq8tICGwTPCi7/Cpwg1nwNNxMhJFT4v/PkOW+Chvlqa3cqty/e7bt/xNDwgrKbQvSUA58ae3tAmukOzezWw8sxCc8pH7aqVK26ntvQVfC+MWmObU+VNAw9Y+TQHItITNP4QfdFvMQHbPM+4s1RJ443dAZGEF3BCUXsMfQkGX48Kck676CfF5up0mtaGXq1yOU6VR+Wyd0ZXMU9hC+oRCKWBJvx9w5o4ZiioidP9ybIXE9G9Ha7ty6njIUW3KOkqqWSGqvYOQDRjFe96wsAoYwT8VwT6AYKlDctN1OcqKCm5wEQx/V9iT4PBA1KkLhLJRERTAw0/gBoOtPtYPhuH83kNz9Vxoj9Fn7WjLfRVUR+0HPlM3fQo4x1ejR7CJ9gGGDFmkxTpmBYCtAjHvgAZvT/7LcB7EbkSpMylN2Jm5uwpJcgwztmwiGNFaXehQuZH3431Pdv7MKD9vHOWR4zlJSnzR372UnG8R1ZHBDdfMGhMf5K6WUyN+t0YPJi8c9NEJvmSRS84DD++QiMLBRSViCeILzTaiNtrR+c6e/CeHP9NgppICvmeyB4YwZEiZ1emSUKBxX0wWSpFDPre6MYQ/KYizNyUOtgbrscGeWs,iv:LLePJci6UXCpzaexsf0e3X70FwnexQtmltITBBItpqk=,tag:WnXUyxgXnrgV0StaWJY0ZA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPamhyZ1dvekgrakVjVWJo
        dWtDRUF2eUZyUktwK1VPbUNqQXdRMU01ZFhzCkk2eERGN2JHemxzMVhHNzRZMEFP
        VW9EQmdiQmh5NXBLRnQybzBZWW5rOHMKLS0tIEY5MUNzM0V2R05oVER4MVNvS2Z1
        RU1ra1BobzBoMUt1b2FpVzBDbFBZSjQKnWY8l73NYnslimz1XQd4N94NNY9EUrYL
        5d5M94vQ7K2KzWzk5u7L4L2I2JBJHdms1OM05cCDE1OMrTBQlc/BCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-13T14:59:10Z"
  mac: ENC[AES256_GCM,data:9HvKt1j7Wmo4VpWEDeuaBJpwB4/s4C7NBKc8DQgIIbYIEtB5wazrY4LCJGySp2ZWe3aqTa+MGqqQbz5njq+dnmypBOWFIlQPIL8GMQ3AvGGVgEDdLmuCrREXweOnogB3BlPprsLASKcUuqNuG+slE+N4peaEk9e3rgxdhwR8SJM=,iv:PXUwEM5kxgigvyTjtqTK8+YZKiBtRauXFlf7liN98lc=,tag:huE5HyR6QO6MHAthLi+fEw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
