apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lalXPmOWSnaZKmaw8SaB,iv:F1iqDSh2KsUFQScmSHL8TMq9cr1yq59e2RnaBT+m8dw=,tag:vDo9ckEsx1KGk6YrcympwA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS3NpUURwa3JDNUZlM3RC
        WnhqeUE1TjZiOFRMTEdRUDBLTzRONmpCd0ZJCkpRVThTMTNLYy9BTmpYMGpPdkkx
        YUZMRkhySjBoTW5hZlo4cHJYRUhmYVEKLS0tIERlK0ptK0xWYXpOQUdqY0dPSHFZ
        VlRJL3VrMzJnRUUyK085YkcxNE55MW8Kg2u1aJXW+yzIg9eOqhYx3uf8L/heAeCL
        1TSJDnj4gPn1F3AMRM0iBvYfwpRbrls+kF3o+1b85iZDvC9oaGHNaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T13:56:00Z"
  mac: ENC[AES256_GCM,data:obnMsubf1vvUKWW4+i5mIEZ5l+XKV+yn2k9qO8fy2+woYhGo4yda1gbeiF6df0t9Yjj91C9kUhwPO9nwPbeTgJL3Ts+lGkkiIMBq0yv6QoCJwQkxQt3a2GV7YlMnzm7H3Dv7iMupJsiin4YT2XeAswFvKgYZKrN+dpKBJIbc7XU=,iv:mHg1hZ+qrdFQ5TPLPWwUrrbEjrgagsvuOxFbqCZim6U=,tag:gNtXXugezXUmiQM/XopbnA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
