apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:mt2G/aHROJwipTW6GEzvrGw434mhXarsMj3SRPyfXIFhTPUp9sbkbjQCbfUQKkjyAIXgZdwdf9DJgPnMgt+CUmujdJnp99qzd+g=,iv:qEq/dC0qk6i9MviUhu2NlISRdncKNRHgynnpuyP8wH4=,tag:DOVJAUKd7Uf7gYT+uEukQw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVldhZXRHa0RMbG5oL0Z4
        UnEwRGl0UDhrUUpudEJPMGdVVzJnblRmS1g0Ck00dTRvRVh5TGZMQzNZTlFITkUr
        cHZ4UmdOZWM3YUhlSHFVcFMyL2RiM00KLS0tIDc0b1hWYks3Y1NBUndadHEzTE9R
        LzRTVmlkbDZRY0NkVEdZVDZVSXFYS28KdXPgZC9R+SN703rbwyjZnUXBlrveu8JM
        bUje1LyIwk4gEyGRfhzIUSh2AMPuxmeUR69Tsw6GAslNh5SmUJbOxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T14:50:15Z"
  mac: ENC[AES256_GCM,data:DTrxHx1yEc8+W3VTymKr+5Sgi7WOkmA/mKvUlnZswhuqQVmHK3b+t5S3IGimIHSHMEeMl9skaYHLoK/NN8n0OMi9lizzKBfWmGEpZQJFBROl9ZJkWcHOZSyztpy9yDV1Wj2DGiwYCs3cPCb/Fe3PKY9xJ1PCEwxc23MbC52SW3A=,iv:DNoD+dz+NH1D1qC26JP5dCJ0Cx7VKe4KgyFUF5S+YZc=,tag:q/KShUv5NLrGMHg4derdkg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
