apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:6bvbbqGR2W5r5tKxs0UgZAUlKGhQFu7iundKDXh8nuqHgy5MiN/lvIGyzFzCKWydNGWwpTWURjBDrLzQgCLto2V2d6phqYuOaoU=,iv:WpHyD9j7MsMg9WOt29vFGurzs/+su/gYzzeENCY2cb8=,tag:c/iORJSqE8cra4wnrw2h3w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N2FQL291WHlYV3VoTFJr
        WWFXa2t4WTlzV2pSOEF5d2lvZ21NWjcwbXpVCnJvZzM3SWpCUGl1OUxmczhnSXlo
        NnRHczhXWi9qR0pWQTBGMEpPWWhPNjgKLS0tIFI1cThwRGM3KytVeVQ1amo2cmxj
        THBINVRtUENPREh5ZTUwVnRET0dtL0EKw+dq6Hb0dk6ERvJcF37xSMpukBFyGKbp
        f2WbfljMjD7OZlTIjlkovKEeFZrQ7lUAVhPQ+/0p+O3XY4VTqptIMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T13:56:00Z"
  mac: ENC[AES256_GCM,data:5iHLZAAwDaZvL8z5rgC5GmZ77a90ZCTXKb/L+xC2Lr1OiIJYnNVxkMi536QmsSOtjIecZLlNcoX8wD4RCDBWKdiwhBSwYZDb2z1wuWe6L3eFv9HQ4pcKeoOAz7DmJR1QAVrdlOYvaQxG7X0nJHYjYXtAy3KgPszG9qSPVEnPU1Y=,iv:7via8IiYrObbVyj+syNkCYrPDJ+F6n9Tac/iaaeSADY=,tag:RbsAzk/QRcTi5685wbCRzg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
