apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:+qAGCpfmlWNgwNPXg/j7iIeLqPJu059q6+IY5lVUdJc7gmUdZNcSugH1T8FWym94bcA24yPXycDpCAw3dTqOJ7ABtjudU01zkR4=,iv:Pb7HjZrBJ+7jRmPrYPtpTY1Od2zN9RtRXhevoggZ6fE=,tag:nXCqp8QP0rMULG4rtyXjBQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1j5a8hm27srcfu4cv5kpq92d747w77mrktegv0ax7x8h85qyx3egsz9kkhc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSVptZ0dyemJpUWJoSVl6
        Qm1Db2xxblRNZ2l1R1BJOHd3b0c1OTFMNmd3ClF0aFljZXNINW51SVBVenRPQ2FB
        S1lxaUpGRE96RDlJY2hSVVJuZXpoc00KLS0tIElZajdtQzkwWGtIdzlqUlRIRGpo
        U3BIdE1oVnRuUE1IZ1I4c0l6M0tlRFkKNG+66Gsyc13lt4dY9zLwwlI9kWoMVOmV
        HR18VPr+fNrk1fBhmUFxPM8hVppsiDv0dRVLHs3TXoPRcZIruYAEbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-25T15:40:10Z"
  mac: ENC[AES256_GCM,data:/NyZLlNHH+YcTHaxQTmmhUeRj6U9rGEEKu4CO+VTMEdm+dcFofJ1R9c3IoR/azk4SwHY1az2+B1ssLayGGYqwwD6s1x10WyMeFMIAsiz2W7EOBbnjbHhx/qAXrgD+gJEH2Yu99z+8GYuq2WvzynyCuBxA7Jk2q/qb+gCuWUBxwc=,iv:WIkE4TbfXxbWZljPaPyFHJXRWc3smx9OA/NGOdQ+tkk=,tag:KQnbp19V/WPCf1cdZR2JDQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
